name: peekaboo
description: A developer utility toolkit for Flutter apps.
version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.0.2
  device_info_plus: ^9.1.2
  package_info_plus: ^5.0.1
  flex_color_scheme: ^7.3.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4

  # Add more as needed

dev_dependencies:
  flutter_test:
    sdk: flutter